language: go

addons:
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}
git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false


matrix:
  include:
    - name: "Linux"
      env:
        GIMME_OS=linux GIMME_ARCH=amd64
      os: linux
    - name: "MacOS"
      env:
        GIMME_OS=darwin GIMME_ARCH=amd64
      os: osx
    - name: "Windows"
      env:
        GIMME_OS=windows GIMME_ARCH=amd64
      os: windows

install:
  - go get -d -v ./...

script:
  - go build -v ./...
  - sonar-scanner
  #- sudo ./gonetmon