language: go

go:
  - 1.11.12
  - master

env:
  - GO111MODULE=on

os:
  - linux
  - osx
dist: trusty


addons:
  apt:
    packages:
      - libpcap-dev
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}
git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false


#matrix:
#  include:
#    - name: "Linux"
#      os: linux
#      dist: trusty
#      after_script:
#        - sonar-scanner
#    - name: "MacOS"
#      os: osx

    #- name: "Windows"
    #  os: windows
    #  before_install:
    #    - choco install winpcap
    #  script:
    #    - ./gonetmon

install:
  - go get -d -v ./...

script:
  - go build -v ./...

after_success:
  - sonar-scanner
  #- sudo ./gonetmon