language: go

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  #- GIMME_OS=windows GIMME_ARCH=amd64

os:
  - linux
  - osx

addons:
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}
git:
  depth: false # Sonar doesn't like shallow clones

notifications:
  email: false

install:
  - go get -d -v ./...

script:
  - go build -v ./...
  - sonar-scanner
  #- sudo ./gonetmon