language: go

go:
  - 1.11.12
  - 1.12

env:
  - GO111MODULE=on

os:
  - linux
dist: trusty

branches:
  only:
    - dev

addons:
  apt:
    packages:
      - libpcap-dev
  sonarcloud:
    organization: "bytemare-github"
    token:
      secure: ${SONAR_TOKEN}
git:
  depth: false # Sonar doesn't like shallow clones


notifications:
  email: false

    #- name: "Windows"
    #  os: windows
    #  before_install:
    #    - choco install winpcap
    #  script:
    #    - ./gonetmon

install:
  - go mod init
  - go get -d -v ./...

script:
  - go install
  - go run Tests/RealTraffic/RealTraffic.go > /dev/null & go run Tests/sniff_test.go
  #- cd Tests && sudo -E env "PATH=$PATH" go test -cover -coverprofile=c.out ./...

after_success:
  - sonar-scanner
  #- sudo ./gonetmon